# Generated by Django 2.1.5 on 2021-08-02 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('Bilim', 'Bilim'), ('Teknoloji', 'Teknoloji'), ('Spor', 'Spor'), ('Kültür', 'Kültür'), ('Sanat', 'Sanat')], default='Bilim', max_length=20, verbose_name='Makale Kategori'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_subtitle',
            field=models.CharField(choices=[('Sağlık', 'Sağlık'), ('Araba', 'Araba'), ('Futbol', 'Futbol'), ('Film', 'Film'), ('Yapay Zeka', 'Yapay Zeka')], default='Bilim', max_length=20, verbose_name='Makale Alt Başlıgı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
