# Generated by Django 2.1.5 on 2021-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210802_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_subtitle',
            field=models.CharField(choices=[('Sağlık', 'Sağlık'), ('Araba', 'Araba'), ('Futbol', 'Futbol'), ('Film', 'Film'), ('Yazılım', 'Yazılım')], default='Yazılım', max_length=150, verbose_name='Makale Alt Başlıgı'),
        ),
    ]
