# Generated by Django 2.1.5 on 2021-08-02 18:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20210802_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_subtitle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sağlık', 'Sağlık'), ('Araba', 'Araba'), ('Futbol', 'Futbol'), ('Film', 'Film'), ('Yazılım', 'Yazılım')], max_length=32),
        ),
    ]
