# Generated by Django 2.1.5 on 2021-08-02 20:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20210802_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=ckeditor.fields.RichTextField(verbose_name='Yorum'),
        ),
    ]
