# Generated by Django 2.1.5 on 2021-08-03 17:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20210802_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_subtitle',
            new_name='category_subtitle',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Yorum'),
        ),
    ]
