# Generated by Django 2.1.5 on 2021-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20210803_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_subtitle',
            field=models.CharField(default='', max_length=100, verbose_name='Alt Başlıklar'),
            preserve_default=False,
        ),
    ]
