# Generated by Django 2.1.5 on 2021-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_article_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_subtitle',
            field=models.TextField(max_length=100, verbose_name='Alt Metin'),
        ),
    ]
