# Generated by Django 2.1.5 on 2021-08-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20210815_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
