# Generated by Django 2.1.5 on 2021-08-15 17:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', ckeditor.fields.RichTextField(verbose_name='Yanıt')),
                ('reply_author', models.CharField(max_length=50, verbose_name='İsim')),
                ('reply_date', models.DateTimeField(auto_now_add=True)),
                ('reply_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Yanıta Fotograf Ekleyin')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Comment', verbose_name='Yorum'),
        ),
    ]
