# Generated by Django 2.1.5 on 2021-08-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_auto_20210815_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
