# Generated by Django 2.1.5 on 2021-07-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='UserAccount',
        ),
    ]
