# Generated by Django 2.1.5 on 2021-07-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210726_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account_avatar',
        ),
    ]
