# Generated by Django 2.1.5 on 2021-07-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_useraccount_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf ekle'),
        ),
    ]
