# Generated by Django 2.1.5 on 2021-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20210728_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Biyografi ekle'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='birthdate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Doğum Tarihi ekle'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Şehir ekle'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ülke ekle'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meslek ekle'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Website ekle'),
        ),
    ]
