# Generated by Django 2.1.5 on 2021-08-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20210728_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Editor Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('fullName', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('m', 'Erkek'), ('f', 'Kadın'), ('n', 'Belirtmek İstemiyorum'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=10)),
                ('account_avatar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf ekle')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website ekle')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ülke ekle')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Şehir ekle')),
                ('birthdate', models.CharField(blank=True, max_length=15, null=True, verbose_name='Doğum Tarihi ekle')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meslek ekle')),
                ('biography', models.CharField(blank=True, max_length=150, null=True, verbose_name='Biyografi ekle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
