# Generated by Django 2.1.5 on 2021-08-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_editoraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditorAccount',
        ),
    ]
